# Generated by Django 5.2.11 on 2026-02-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_exemplar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiaCitationValidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('status_reason', models.TextField(blank=True)),
                ('positive_citations', models.IntegerField(default=0)),
                ('negative_citations', models.IntegerField(default=0)),
                ('overruling_citations', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'citation_validity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('source_doc_id', models.CharField(max_length=100)),
                ('case_name', models.CharField(max_length=500)),
                ('citation', models.CharField(max_length=200)),
                ('decision_date', models.DateField(null=True)),
                ('deciding_body', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('case_type', models.CharField(max_length=50)),
                ('court', models.CharField(max_length=20)),
                ('outcome', models.CharField(max_length=50)),
                ('precedential_status', models.CharField(max_length=50)),
                ('cited_by_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiaDocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('confidence', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'document_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiaDocumentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('full_text', models.TextField()),
                ('word_count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'document_texts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiaHeadnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('topic_code', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'headnotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiaHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('legal_issue', models.CharField(max_length=500)),
                ('rule', models.TextField()),
                ('statutory_basis', models.JSONField(null=True)),
                ('confidence', models.FloatField(null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'holdings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiaHoldingEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_id', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'holding_embeddings',
                'managed': False,
            },
        ),
    ]
