# Generated by Django 5.2.11 on 2026-03-07 23:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_exemplar_kind_style_family_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('chat', 'Chat'), ('suggest', 'Suggest')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('stage', models.CharField(blank=True, default='queued', max_length=50)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('response_id', models.CharField(blank=True, default='', max_length=200)),
                ('previous_response_id', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('local_function_rounds', models.PositiveIntegerField(default=0)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_runs', to='editor.documentresearchmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='editor.documentresearchsession')),
                ('user_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_runs', to='editor.documentresearchmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
