"""
Seed document templates with real, useful Tiptap JSON content.
"""
from django.core.management.base import BaseCommand
from editor.models import DocumentType


def _p(text, bold=False, italic=False):
    """Helper to make a paragraph node."""
    marks = []
    if bold:
        marks.append({"type": "bold"})
    if italic:
        marks.append({"type": "italic"})

    if not text:
        return {"type": "paragraph", "content": []}

    content_item = {"type": "text", "text": text}
    if marks:
        content_item["marks"] = marks
    return {"type": "paragraph", "content": [content_item]}


def _h(text, level=1):
    """Helper to make a heading node."""
    return {
        "type": "heading",
        "attrs": {"level": level},
        "content": [{"type": "text", "text": text}],
    }


def _mixed_paragraph(parts):
    """Paragraph with mixed formatting. Parts = list of (text, marks_list)."""
    content = []
    for text, marks in parts:
        item = {"type": "text", "text": text}
        if marks:
            item["marks"] = marks
        content.append(item)
    return {"type": "paragraph", "content": content}


def _bullet_list(items):
    """Create a bullet list from text items."""
    return {
        "type": "bulletList",
        "content": [
            {
                "type": "listItem",
                "content": [_p(item)],
            }
            for item in items
        ],
    }


def _hr():
    return {"type": "horizontalRule"}


TEMPLATES = [
    {
        "name": "I-130 Cover Letter",
        "slug": "i-130-cover-letter",
        "category": "cover_letter",
        "export_format": "cover_letter",
        "icon": "📋",
        "order": 1,
        "description": "Cover letter for I-130 Petition for Alien Relative",
        "template_content": {
            "type": "doc",
            "content": [
                _p("[Date]"),
                _p(""),
                _p("U.S. Citizenship and Immigration Services"),
                _p("[Service Center Name]"),
                _p("[Service Center Address]"),
                _p(""),
                _mixed_paragraph([
                    ("RE: ", [{"type": "bold"}]),
                    ("Form I-130, Petition for Alien Relative", []),
                ]),
                _mixed_paragraph([
                    ("Petitioner: ", [{"type": "bold"}]),
                    ("[Petitioner Full Name]", []),
                ]),
                _mixed_paragraph([
                    ("Beneficiary: ", [{"type": "bold"}]),
                    ("[Beneficiary Full Name]", []),
                ]),
                _p(""),
                _p("Dear USCIS Officer:"),
                _p(""),
                _p("Please find enclosed the Form I-130, Petition for Alien Relative, filed by [Petitioner Name] (\"Petitioner\") on behalf of [his/her] [relationship], [Beneficiary Name] (\"Beneficiary\"). This petition is filed pursuant to Section 201(b) of the Immigration and Nationality Act (\"INA\"), 8 U.S.C. § 1151(b)."),
                _p(""),
                _h("Petitioner's Background", 2),
                _p("[Describe petitioner's immigration status, citizenship, date of naturalization or birth in the US. Include A-number if applicable.]"),
                _p(""),
                _h("Beneficiary's Background", 2),
                _p("[Describe beneficiary's nationality, current immigration status, current location, and relationship to the petitioner.]"),
                _p(""),
                _h("Bona Fide Relationship", 2),
                _p("[For spouse petitions: describe the bona fide nature of the marriage — how they met, when they married, evidence of shared life. For parent/child: establish the qualifying relationship.]"),
                _p(""),
                _h("Enclosed Documentation", 2),
                _p("The following documents are submitted in support of this petition:"),
                _p(""),
                _h("Forms", 3),
                _bullet_list([
                    "Form I-130, Petition for Alien Relative",
                    "Form G-28, Notice of Entry of Appearance",
                    "[Form I-130A, Supplemental Information (if applicable)]",
                ]),
                _p(""),
                _h("Identity Documents", 3),
                _bullet_list([
                    "[Petitioner's U.S. passport / naturalization certificate / birth certificate]",
                    "[Beneficiary's passport biographical page]",
                    "[Marriage certificate (if spouse petition)]",
                    "[Birth certificate(s) establishing relationship]",
                ]),
                _p(""),
                _h("Evidence of Bona Fide Relationship", 3),
                _bullet_list([
                    "[Joint bank account statements]",
                    "[Joint lease or mortgage documents]",
                    "[Joint utility bills]",
                    "[Photographs of the couple together]",
                    "[Affidavits from friends and family]",
                ]),
                _p(""),
                _h("Conclusion", 2),
                _p("Based on the foregoing, Petitioner respectfully requests that this I-130 petition be approved. Should you require any additional information or documentation, please do not hesitate to contact our office."),
                _p(""),
                _p("Respectfully submitted,"),
                _p(""),
                _p(""),
                _p("Chris Hammond"),
                _p("Attorney for Petitioner"),
                _p("Hammond Law, PLLC"),
            ],
        },
    },
    {
        "name": "Defensive Asylum Brief",
        "slug": "defensive-asylum-brief",
        "category": "brief",
        "export_format": "court_brief",
        "icon": "⚖️",
        "order": 2,
        "description": "Merits brief for defensive asylum claim in Immigration Court",
        "template_content": {
            "type": "doc",
            "content": [
                _p("UNITED STATES DEPARTMENT OF JUSTICE", bold=True),
                _p("EXECUTIVE OFFICE FOR IMMIGRATION REVIEW", bold=True),
                _p("IMMIGRATION COURT — [CITY]", bold=True),
                _p(""),
                _hr(),
                _p(""),
                _mixed_paragraph([
                    ("In the Matter of: ", []),
                    ("[RESPONDENT NAME]", [{"type": "bold"}]),
                ]),
                _p(""),
                _mixed_paragraph([
                    ("A# ", []),
                    ("[A-Number]", [{"type": "bold"}]),
                ]),
                _p(""),
                _mixed_paragraph([
                    ("In Removal Proceedings", [{"type": "italic"}]),
                ]),
                _p(""),
                _hr(),
                _p(""),
                _h("RESPONDENT'S BRIEF IN SUPPORT OF APPLICATION FOR ASYLUM, WITHHOLDING OF REMOVAL, AND PROTECTION UNDER THE CONVENTION AGAINST TORTURE", 1),
                _p(""),
                _h("I. STATEMENT OF THE CASE", 1),
                _p("[Respondent Name] (\"Respondent\"), by and through undersigned counsel, respectfully submits this brief in support of [his/her] applications for asylum under INA § 208, 8 U.S.C. § 1158; withholding of removal under INA § 241(b)(3), 8 U.S.C. § 1231(b)(3); and protection under the Convention Against Torture (\"CAT\") pursuant to 8 C.F.R. § 1208.16(c)."),
                _p(""),
                _h("II. STATEMENT OF FACTS", 1),
                _p("[Provide a detailed narrative of the respondent's background, the persecution or harm suffered, the circumstances leading to flight from the home country, and the basis for the asylum claim. Include specific dates, locations, perpetrators, and injuries. Reference the respondent's declaration and supporting evidence throughout.]"),
                _p(""),
                _h("A. Country Conditions", 2),
                _p("[Describe relevant country conditions that corroborate the respondent's claim. Reference State Department reports, human rights organizations, news articles, and expert declarations.]"),
                _p(""),
                _h("III. LEGAL STANDARD", 1),
                _p(""),
                _h("A. Asylum — INA § 208", 2),
                _p("To establish eligibility for asylum, an applicant must demonstrate that [he/she] is a \"refugee\" within the meaning of INA § 101(a)(42)(A), 8 U.S.C. § 1101(a)(42)(A). A refugee is a person who is unable or unwilling to return to [his/her] country of nationality \"because of persecution or a well-founded fear of persecution on account of race, religion, nationality, membership in a particular social group, or political opinion.\" Id."),
                _p(""),
                _p("An applicant may establish eligibility by demonstrating either past persecution or a well-founded fear of future persecution. 8 C.F.R. § 1208.13(b). A showing of past persecution creates a rebuttable presumption of a well-founded fear of future persecution. 8 C.F.R. § 1208.13(b)(1)."),
                _p(""),
                _h("B. Withholding of Removal — INA § 241(b)(3)", 2),
                _p("To qualify for withholding of removal, the applicant must demonstrate that [his/her] \"life or freedom would be threatened\" in the proposed country of removal on account of a protected ground. INA § 241(b)(3)(A), 8 U.S.C. § 1231(b)(3)(A). The standard requires a showing that persecution is \"more likely than not.\" INS v. Stevic, 467 U.S. 407, 429-30 (1984)."),
                _p(""),
                _h("C. Convention Against Torture — 8 C.F.R. § 1208.16(c)", 2),
                _p("To establish eligibility for protection under the CAT, the applicant must demonstrate that it is \"more likely than not\" that [he/she] would be tortured if removed to the proposed country of removal. 8 C.F.R. § 1208.16(c)(2). Torture must be \"inflicted by or at the instigation of or with the consent or acquiescence of a public official or other person acting in an official capacity.\" 8 C.F.R. § 1208.18(a)(1)."),
                _p(""),
                _h("IV. ARGUMENT", 1),
                _p(""),
                _h("A. Respondent Has Established Past Persecution", 2),
                _p("[Argue that the harm suffered constitutes persecution. Cite to specific facts and evidence. Reference relevant BIA and circuit court precedent on what constitutes persecution.]"),
                _p(""),
                _h("B. The Persecution Was on Account of a Protected Ground", 2),
                _p("[Establish the nexus between the persecution and one or more of the five protected grounds. For PSG claims, define the proposed group and show it satisfies particularity, social distinction, and immutability requirements per Matter of M-E-V-G-, 26 I&N Dec. 227 (BIA 2014) and Matter of W-G-R-, 26 I&N Dec. 208 (BIA 2014).]"),
                _p(""),
                _h("C. Respondent Has a Well-Founded Fear of Future Persecution", 2),
                _p("[If applicable, argue that the respondent has an independently well-founded fear of future persecution, even apart from the presumption arising from past persecution. Address internal relocation if relevant.]"),
                _p(""),
                _h("D. Respondent Merits a Favorable Exercise of Discretion", 2),
                _p("[For asylum claims (which are discretionary), briefly argue that the positive factors outweigh any negative factors. Reference Matter of Pula, 19 I&N Dec. 467 (BIA 1987).]"),
                _p(""),
                _h("E. Alternatively, Respondent Is Entitled to Withholding of Removal", 2),
                _p("[Argue the higher standard is met, or that even if asylum is denied, withholding should be granted.]"),
                _p(""),
                _h("F. Alternatively, Respondent Is Entitled to Protection Under the CAT", 2),
                _p("[Argue the CAT claim, focusing on government involvement/acquiescence and the likelihood of torture upon return.]"),
                _p(""),
                _h("V. CONCLUSION", 1),
                _p("For the foregoing reasons, Respondent respectfully requests that this Honorable Court grant [his/her] application for asylum. In the alternative, Respondent requests withholding of removal under INA § 241(b)(3) or, in the further alternative, protection under the Convention Against Torture."),
                _p(""),
                _p("Respectfully submitted,"),
                _p(""),
                _p(""),
                _p("Chris Hammond"),
                _p("Attorney for Respondent"),
                _p("Hammond Law, PLLC"),
                _p("[Date]"),
            ],
        },
    },
    {
        "name": "Bond Brief",
        "slug": "bond-brief",
        "category": "brief",
        "export_format": "court_brief",
        "icon": "🔓",
        "order": 3,
        "description": "Brief in support of bond or custody redetermination request",
        "template_content": {
            "type": "doc",
            "content": [
                _p("UNITED STATES DEPARTMENT OF JUSTICE", bold=True),
                _p("EXECUTIVE OFFICE FOR IMMIGRATION REVIEW", bold=True),
                _p("IMMIGRATION COURT — [CITY]", bold=True),
                _p(""),
                _hr(),
                _p(""),
                _mixed_paragraph([
                    ("In the Matter of: ", []),
                    ("[RESPONDENT NAME]", [{"type": "bold"}]),
                ]),
                _p(""),
                _mixed_paragraph([
                    ("A# ", []),
                    ("[A-Number]", [{"type": "bold"}]),
                ]),
                _p(""),
                _hr(),
                _p(""),
                _h("RESPONDENT'S BRIEF IN SUPPORT OF BOND REDETERMINATION", 1),
                _p(""),
                _h("I. INTRODUCTION", 1),
                _p("[Respondent Name] (\"Respondent\"), by and through undersigned counsel, respectfully requests that this Honorable Court set a reasonable bond or, in the alternative, release Respondent on [his/her] own recognizance. Respondent is not a flight risk and does not pose a danger to the community."),
                _p(""),
                _h("II. BACKGROUND", 1),
                _p("[Provide a brief overview: who the respondent is, nationality, how long in the US, family ties, when and why they were detained, current detention facility.]"),
                _p(""),
                _h("III. LEGAL STANDARD", 1),
                _p("Under INA § 236(a), 8 U.S.C. § 1226(a), an alien who is not subject to mandatory detention may be released on bond of at least $1,500 or on conditional parole. The Immigration Judge has authority to redetermine bond conditions pursuant to 8 C.F.R. § 1236.1(d)."),
                _p(""),
                _p("In making a bond determination, the Immigration Judge considers two factors: (1) whether the alien is a danger to the community, and (2) whether the alien is a flight risk. Matter of Guerra, 24 I&N Dec. 37 (BIA 2006). The respondent bears the burden of demonstrating that [he/she] does not pose a danger and is not a flight risk. Id."),
                _p(""),
                _p("In evaluating these factors, the Immigration Judge should consider the totality of the circumstances, including:"),
                _bullet_list([
                    "Fixed address and length of residence in the community",
                    "Employment history",
                    "Family ties in the United States",
                    "Immigration history and prior compliance with court orders",
                    "Criminal record (or lack thereof)",
                    "Participation in community organizations",
                    "Manner of entry to the United States",
                ]),
                _p("See Matter of Guerra, 24 I&N Dec. at 40."),
                _p(""),
                _h("IV. ARGUMENT", 1),
                _p(""),
                _h("A. Respondent Is Not a Danger to the Community", 2),
                _p("[Argue that the respondent has no criminal history, or that any criminal history is minor/remote. Highlight positive character evidence, employment, community involvement.]"),
                _p(""),
                _h("B. Respondent Is Not a Flight Risk", 2),
                _p("[Argue that the respondent has strong ties to the community — family, employment, residence, length of time in the US. Note any prior compliance with immigration proceedings, attendance at hearings, etc.]"),
                _p(""),
                _h("C. The Equities Support Release on Bond", 2),
                _p("[Address the totality of circumstances. Discuss U.S. citizen or LPR family members, especially children. Note respondent's roots in the community and reliability.]"),
                _p(""),
                _h("V. CONCLUSION", 1),
                _p("For the foregoing reasons, Respondent respectfully requests that this Honorable Court set bond at a reasonable amount, or in the alternative, release Respondent on [his/her] own recognizance."),
                _p(""),
                _p("Respectfully submitted,"),
                _p(""),
                _p(""),
                _p("Chris Hammond"),
                _p("Attorney for Respondent"),
                _p("Hammond Law, PLLC"),
                _p("[Date]"),
            ],
        },
    },
    {
        "name": "RFE Response",
        "slug": "rfe-response",
        "category": "cover_letter",
        "export_format": "cover_letter",
        "icon": "📨",
        "order": 4,
        "description": "Response to USCIS Request for Evidence (RFE)",
        "template_content": {
            "type": "doc",
            "content": [
                _p("[Date]"),
                _p(""),
                _p("U.S. Citizenship and Immigration Services"),
                _p("[Service Center Name]"),
                _p("[Service Center Address]"),
                _p(""),
                _mixed_paragraph([
                    ("RE: ", [{"type": "bold"}]),
                    ("Response to Request for Evidence", []),
                ]),
                _mixed_paragraph([
                    ("Receipt Number: ", [{"type": "bold"}]),
                    ("[Receipt Number]", []),
                ]),
                _mixed_paragraph([
                    ("Applicant/Petitioner: ", [{"type": "bold"}]),
                    ("[Name]", []),
                ]),
                _mixed_paragraph([
                    ("Beneficiary: ", [{"type": "bold"}]),
                    ("[Name, if applicable]", []),
                ]),
                _mixed_paragraph([
                    ("Form Type: ", [{"type": "bold"}]),
                    ("[I-130 / I-485 / I-601, etc.]", []),
                ]),
                _p(""),
                _p("Dear USCIS Officer:"),
                _p(""),
                _p("This letter is submitted in response to the Request for Evidence (\"RFE\") issued on [date of RFE] in the above-referenced matter. We respectfully submit the following evidence and argument to address each issue raised in the RFE."),
                _p(""),
                _h("Issue 1: [Title from RFE]", 2),
                _p("[Quote the specific language from the RFE describing what is being requested.]"),
                _p(""),
                _h("Response", 3),
                _p("[Provide a clear, organized response. Reference specific evidence being submitted. Cite applicable law or policy that supports your position.]"),
                _p(""),
                _h("Issue 2: [Title from RFE]", 2),
                _p("[Quote the specific language from the RFE.]"),
                _p(""),
                _h("Response", 3),
                _p("[Response to issue 2.]"),
                _p(""),
                _h("[Add additional issues as needed]", 2),
                _p(""),
                _h("Enclosed Documentation", 2),
                _p("In support of this response, the following documents are enclosed:"),
                _p(""),
                _bullet_list([
                    "[Document 1 — description]",
                    "[Document 2 — description]",
                    "[Document 3 — description]",
                ]),
                _p(""),
                _h("Conclusion", 2),
                _p("Based on the foregoing evidence and argument, we respectfully submit that the requirements of the RFE have been satisfied and request that the application/petition be approved. Should you require any additional information, please do not hesitate to contact our office."),
                _p(""),
                _p("Respectfully submitted,"),
                _p(""),
                _p(""),
                _p("Chris Hammond"),
                _p("Attorney for [Applicant/Petitioner]"),
                _p("Hammond Law, PLLC"),
            ],
        },
    },
    {
        "name": "I-601/601A Hardship Waiver Brief",
        "slug": "hardship-waiver-brief",
        "category": "brief",
        "export_format": "court_brief",
        "icon": "💔",
        "order": 5,
        "description": "Brief in support of extreme hardship waiver application",
        "template_content": {
            "type": "doc",
            "content": [
                _p("[Date]"),
                _p(""),
                _p("U.S. Citizenship and Immigration Services"),
                _p("[Service Center / Field Office]"),
                _p("[Address]"),
                _p(""),
                _mixed_paragraph([
                    ("RE: ", [{"type": "bold"}]),
                    ("Application for Waiver — Form I-601/I-601A", []),
                ]),
                _mixed_paragraph([
                    ("Applicant: ", [{"type": "bold"}]),
                    ("[Applicant Name]", []),
                ]),
                _mixed_paragraph([
                    ("Qualifying Relative: ", [{"type": "bold"}]),
                    ("[QR Name], U.S. [Citizen/LPR]", []),
                ]),
                _p(""),
                _h("BRIEF IN SUPPORT OF EXTREME HARDSHIP WAIVER", 1),
                _p(""),
                _h("I. INTRODUCTION", 1),
                _p("[Applicant Name] (\"Applicant\") respectfully submits this brief in support of [his/her] Application for Waiver of Grounds of Inadmissibility pursuant to INA § 212(a)(9)(B)(v) / INA § 212(i), 8 U.S.C. § 1182. Applicant demonstrates that [his/her] qualifying relative, [QR Name], who is a United States [citizen/lawful permanent resident], would suffer extreme hardship if the waiver is not granted."),
                _p(""),
                _h("II. FACTUAL BACKGROUND", 1),
                _p(""),
                _h("A. Applicant's Background", 2),
                _p("[Describe the applicant's background, entry to the US, family history, and the ground of inadmissibility being waived.]"),
                _p(""),
                _h("B. Qualifying Relative's Background", 2),
                _p("[Describe the qualifying relative — citizenship, occupation, health conditions, ties to the US, relationship with applicant.]"),
                _p(""),
                _h("III. LEGAL STANDARD", 1),
                _p("The Attorney General may grant a waiver of inadmissibility if the applicant demonstrates that refusal of admission would result in \"extreme hardship\" to a qualifying relative who is a U.S. citizen or lawful permanent resident. INA § 212(a)(9)(B)(v)."),
                _p(""),
                _p("Extreme hardship is not defined by statute, but the BIA has identified relevant factors including: the qualifying relative's health conditions, financial impact, educational disruption, personal considerations such as family separation, and country conditions. Matter of Cervantes-Gonzalez, 22 I&N Dec. 560 (BIA 1999)."),
                _p(""),
                _p("USCIS considers hardship factors in the aggregate, and \"the sum of two or more individual hardship factors considered together may be found to constitute extreme hardship.\" Matter of O-J-O-, 21 I&N Dec. 381 (BIA 1996)."),
                _p(""),
                _h("IV. ARGUMENT — EXTREME HARDSHIP TO QUALIFYING RELATIVE", 1),
                _p(""),
                _h("A. Hardship if the Qualifying Relative Remains in the United States (Separation Scenario)", 2),
                _p("[Analyze the hardship to the QR if they stay in the US while the applicant is abroad. Consider: emotional/psychological impact of separation, financial hardship from loss of applicant's contributions, impact on children, loss of caregiving support.]"),
                _p(""),
                _h("B. Hardship if the Qualifying Relative Relocates Abroad (Relocation Scenario)", 2),
                _p("[Analyze the hardship if the QR moves to the applicant's home country. Consider: loss of employment/career, educational disruption for children, diminished quality of life, country conditions, language barriers, loss of community ties, medical care availability.]"),
                _p(""),
                _h("C. Cumulative Impact", 2),
                _p("[Argue that when considered in the aggregate, these hardship factors rise to the level of extreme hardship. The totality of the circumstances demonstrates hardship significantly beyond that which would normally be expected from deportation.]"),
                _p(""),
                _h("V. CONCLUSION", 1),
                _p("For the foregoing reasons, the Applicant has demonstrated that [his/her] qualifying relative would suffer extreme hardship in both the separation and relocation scenarios. Applicant respectfully requests that this waiver application be approved."),
                _p(""),
                _p("Respectfully submitted,"),
                _p(""),
                _p(""),
                _p("Chris Hammond"),
                _p("Attorney for Applicant"),
                _p("Hammond Law, PLLC"),
            ],
        },
    },
    {
        "name": "Motion to Reopen",
        "slug": "motion-to-reopen",
        "category": "motion",
        "export_format": "court_brief",
        "icon": "🔄",
        "order": 6,
        "description": "Motion to reopen removal proceedings before the Immigration Court or BIA",
        "template_content": {
            "type": "doc",
            "content": [
                _p("UNITED STATES DEPARTMENT OF JUSTICE", bold=True),
                _p("EXECUTIVE OFFICE FOR IMMIGRATION REVIEW", bold=True),
                _p("[IMMIGRATION COURT / BOARD OF IMMIGRATION APPEALS]", bold=True),
                _p(""),
                _hr(),
                _p(""),
                _mixed_paragraph([
                    ("In the Matter of: ", []),
                    ("[RESPONDENT NAME]", [{"type": "bold"}]),
                ]),
                _mixed_paragraph([
                    ("A# ", []),
                    ("[A-Number]", [{"type": "bold"}]),
                ]),
                _p(""),
                _hr(),
                _p(""),
                _h("MOTION TO REOPEN REMOVAL PROCEEDINGS", 1),
                _p(""),
                _h("I. INTRODUCTION", 1),
                _p("[Respondent Name] (\"Respondent\"), by and through undersigned counsel, respectfully moves to reopen the above-captioned removal proceedings pursuant to INA § 240(c)(7), 8 U.S.C. § 1229a(c)(7), and 8 C.F.R. § 1003.23."),
                _p(""),
                _h("II. PROCEDURAL HISTORY", 1),
                _p("[Describe the procedural history: when proceedings began, what happened (in absentia order, denied application, etc.), date of final order, any prior motions.]"),
                _p(""),
                _h("III. LEGAL STANDARD", 1),
                _p("A motion to reopen must be filed within 90 days of the final order of removal. INA § 240(c)(7)(C)(i). The motion must state the new facts that will be proven at a hearing if the motion is granted and must be supported by affidavits or other evidentiary material. INA § 240(c)(7)(B)."),
                _p(""),
                _p("[If filing an untimely motion or based on in absentia order, include the applicable exception:]"),
                _p(""),
                _p("[FOR IN ABSENTIA CASES: An in absentia order may be rescinded upon a motion to reopen filed at any time if the alien demonstrates that the alien did not receive notice in accordance with INA § 239(a)(1) or (2), or the alien demonstrates that the alien was in Federal or State custody and the failure to appear was through no fault of the alien. INA § 240(b)(5)(C).]"),
                _p(""),
                _p("[FOR CHANGED COUNTRY CONDITIONS: There is no time limit on a motion to reopen based on changed country conditions in asylum cases. INA § 240(c)(7)(C)(ii).]"),
                _p(""),
                _h("IV. ARGUMENT", 1),
                _p("[Present the substantive argument for reopening. Address the specific legal basis — new evidence, changed country conditions, ineffective assistance of counsel (with Lozada compliance), lack of notice, etc.]"),
                _p(""),
                _h("V. CONCLUSION", 1),
                _p("For the foregoing reasons, Respondent respectfully requests that this Honorable Court grant this Motion to Reopen."),
                _p(""),
                _p("Respectfully submitted,"),
                _p(""),
                _p(""),
                _p("Chris Hammond"),
                _p("Attorney for Respondent"),
                _p("Hammond Law, PLLC"),
                _p("[Date]"),
            ],
        },
    },
    {
        "name": "Client Declaration",
        "slug": "client-declaration",
        "category": "declaration",
        "export_format": "declaration",
        "icon": "✋",
        "order": 7,
        "description": "Sworn declaration template for client's statement",
        "template_content": {
            "type": "doc",
            "content": [
                _h("DECLARATION OF [CLIENT NAME]", 1),
                _p(""),
                _p("I, [Client Full Name], hereby declare under penalty of perjury under the laws of the United States that the following is true and correct:"),
                _p(""),
                _p("[I was born on [date of birth] in [city, country]. I am a citizen and national of [country].]"),
                _p(""),
                _p("[Describe your personal background — family, education, occupation in home country.]"),
                _p(""),
                _p("[Describe the events that caused you to leave your country. Be specific about dates, locations, names of persecutors, and what happened to you. Describe any injuries, threats, or harm in detail.]"),
                _p(""),
                _p("[Describe any attempts to seek protection from authorities in your home country and the result.]"),
                _p(""),
                _p("[Describe your journey to the United States and your entry.]"),
                _p(""),
                _p("[Describe why you are afraid to return to your home country. What do you believe would happen to you if you were sent back?]"),
                _p(""),
                _p("[Describe your life in the United States — family, community, employment, any other relevant information.]"),
                _p(""),
                _p("I declare under penalty of perjury that the foregoing is true and correct."),
                _p(""),
                _p("Executed on [date], in [city, state]."),
                _p(""),
                _p(""),
                _p("____________________________"),
                _p("[Client Full Name]"),
            ],
        },
    },
    {
        "name": "I-751 Cover Letter",
        "slug": "i-751-cover-letter",
        "category": "cover_letter",
        "export_format": "cover_letter",
        "icon": "💍",
        "order": 8,
        "description": "Cover letter for I-751 Petition to Remove Conditions on Residence",
        "template_content": {
            "type": "doc",
            "content": [
                _p("[Date]"),
                _p(""),
                _p("U.S. Citizenship and Immigration Services"),
                _p("[Service Center Name]"),
                _p("[Service Center Address]"),
                _p(""),
                _mixed_paragraph([
                    ("RE: ", [{"type": "bold"}]),
                    ("Form I-751, Petition to Remove Conditions on Residence", []),
                ]),
                _mixed_paragraph([
                    ("Petitioner: ", [{"type": "bold"}]),
                    ("[Conditional Resident Name]", []),
                ]),
                _mixed_paragraph([
                    ("Joint Petitioner: ", [{"type": "bold"}]),
                    ("[U.S. Citizen Spouse Name]", []),
                ]),
                _mixed_paragraph([
                    ("A#: ", [{"type": "bold"}]),
                    ("[A-Number]", []),
                ]),
                _p(""),
                _p("Dear USCIS Officer:"),
                _p(""),
                _p("Please find enclosed the Form I-751, Petition to Remove Conditions on Residence, filed jointly by [Conditional Resident Name] and [U.S. Citizen Spouse Name]. The petitioner was granted conditional permanent resident status on [date] and the conditions must be removed pursuant to INA § 216(c), 8 U.S.C. § 1186a(c)."),
                _p(""),
                _h("Continued Bona Fide Marriage", 2),
                _p("The petitioner and the joint petitioner continue to reside together as husband and wife at [address]. They were married on [date] in [location] and their marriage remains bona fide. The following evidence demonstrates the ongoing validity and good faith of the marriage:"),
                _p(""),
                _h("Evidence Submitted", 2),
                _p(""),
                _h("Joint Financial Documents", 3),
                _bullet_list([
                    "[Joint bank account statements covering the two-year conditional period]",
                    "[Joint tax returns (Form 1040) for [year(s)]]",
                    "[Joint lease/mortgage showing both names]",
                ]),
                _p(""),
                _h("Joint Residence", 3),
                _bullet_list([
                    "[Utility bills in both names or at shared address]",
                    "[Driver's licenses showing same address]",
                    "[Mail received at shared address]",
                ]),
                _p(""),
                _h("Shared Life", 3),
                _bullet_list([
                    "[Joint insurance policies (health, auto, life)]",
                    "[Photographs of the couple together over the conditional period]",
                    "[Birth certificate of child born during marriage, if applicable]",
                    "[Affidavits from friends and family attesting to the bona fide nature of the marriage]",
                ]),
                _p(""),
                _h("Conclusion", 2),
                _p("Based on the foregoing, the petitioners have demonstrated that their marriage was entered into in good faith and has continued in good faith throughout the period of conditional residence. We respectfully request that the conditions on residence be removed."),
                _p(""),
                _p("Respectfully submitted,"),
                _p(""),
                _p(""),
                _p("Chris Hammond"),
                _p("Attorney for Petitioner"),
                _p("Hammond Law, PLLC"),
            ],
        },
    },
]


class Command(BaseCommand):
    help = "Seed document templates"

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for t in TEMPLATES:
            obj, was_created = DocumentType.objects.update_or_create(
                slug=t["slug"],
                defaults={
                    "name": t["name"],
                    "category": t["category"],
                    "template_content": t["template_content"],
                    "export_format": t["export_format"],
                    "description": t["description"],
                    "icon": t["icon"],
                    "order": t["order"],
                },
            )
            if was_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(
            self.style.SUCCESS(f"Templates: {created} created, {updated} updated")
        )
